# 配置名称: clash/surge 订阅转换
# 配置作者: wmsxwdsh
# 适用版本：多端通用
# 更新时间: 2025-03-18

[custom]
# > wmsxwdsh Personal Rules：https://raw.githubusercontent.com/wmsxwdsh/ClashSub/main/wmsxwdsh20230715.ini
# > blackmatrix7 Clash Rules：https://github.com/blackmatrix7/ios_rule_script/tree/master/rule/Clash
# > ACL4SSR Clash Config：https://github.com/ACL4SSR/ACL4SSR/tree/master/Clash/config

exclude_remarks=(距离|重置|过期|到期|剩余|GB|Traffic|官方|官网|客户端|X2|x2|建议|邮箱|更新|电报|失联|订阅|导航|节点|升级)

# 五大区 + 澳门
emoji=(香港|广港|HK|HKG|Hong Kong),🇭🇰
emoji=(澳门|MO|Macao|Macau),🇲🇴
emoji=(台湾|TW|TWN|Taiwan),🇨🇳
emoji=(新加坡|狮城|SG|SGP|Singapore),🇸🇬
emoji=(日本|沪日|JP|JPN|Japan),🇯🇵
emoji=(美国|US|USA|United States),🇺🇸
# 欧洲
emoji=(白俄罗斯),🇧🇾
emoji=(俄罗斯|莫斯科|圣彼得堡|RUS|Russia|Moscow|Petersburg),🇷🇺
emoji=(爱沙尼亚),🇪🇪
emoji=(拉脱维亚),🇱🇻
emoji=(立陶宛|Lithuania),🇱🇹
emoji=(波兰|Poland),🇵🇱
emoji=(乌克兰|Ukraine),🇺🇦
emoji=(摩尔多瓦|Moldova),🇲🇩
emoji=(冰岛|Iceland),🇮🇸
emoji=(爱尔兰|Ireland|Irish),🇮🇪
emoji=(马恩岛|曼岛),🇮🇲
emoji=(英国|伦敦|UK|United Kingdom|Britain|London|Coventry),🇬🇧
emoji=(法国|FR|France|Paris),🇫🇷
emoji=(摩纳哥),🇲🇨
emoji=(德国|DE|Germany|Berlin),🇩🇪
emoji=(捷克|Czech),🇨🇿
emoji=(斯洛伐克),🇸🇰
emoji=(法罗群岛),🇫🇴
emoji=(丹麦|Denmark),🇩🇰
emoji=(挪威|Norway),🇳🇴
emoji=(瑞典|Sweden),🇸🇪
emoji=(奥兰|奥兰群岛),🇦🇽
emoji=(芬兰|Finland),🇫🇮
emoji=(荷兰|Holland|Netherlands),🇳🇱
emoji=(比利时|Belgium),🇧🇪
emoji=(卢森堡|Luxembourg),🇱🇺
emoji=(安道尔|Andorra),🇦🇩
emoji=(直布罗陀),🇬🇮
emoji=(西班牙|Spain|España|Euskaltel),🇪🇸
emoji=(葡萄牙|Portugal),🇵🇹
emoji=(瑞士|Switzerland),🇨🇭
emoji=(列支敦士登|Liechtenstein),🇱🇮
emoji=(奥地利|维也纳|AT|Austria|Austrian|Vienna),🇦🇹
emoji=(匈牙利|Hungary),🇭🇺
emoji=(意大利|Italy|Italia|Rome),🇮🇹
emoji=(梵蒂冈),🇻🇦
emoji=(圣马力诺),🇸🇲
emoji=(克罗地亚),🇭🇷
emoji=(斯洛文尼亚),🇸🇮
emoji=(波黑|波斯尼亚),🇧🇦
emoji=(黑山),🇲🇪
emoji=(阿尔巴尼亚|Albania),🇦🇱
emoji=(塞尔维亚),🇷🇸
emoji=(北马其顿),🇲🇰
emoji=(希腊|Greece),🇬🇷
emoji=(罗马尼亚|Romania),🇷🇴
emoji=(保加利亚|Bulgaria),🇧🇬
emoji=(马耳他),🇲🇹
# 亚洲
emoji=(蒙古|Mongolia),🇲🇳
emoji=(朝鲜|North Korea),🇰🇵
emoji=(韩国|韩|KR|Korea|KOR|South Korea),🇰🇷
emoji=(不丹|Bhutan),🇧🇹
emoji=(尼泊尔|Nepal),🇳🇵
emoji=(孟加拉国|孟加拉|Bangladesh),🇧🇩
emoji=(马尔代夫|Maldives),🇲🇻
emoji=(斯里兰卡|Sri Lanka),🇱🇰
emoji=(印度|IN|IND|India),🇮🇳
emoji=(印度尼西亚|印尼|ID|IDN|Indonesia),🇮🇩
emoji=(马来西亚|Malaysia),🇲🇾
emoji=(菲律宾|PH|Philippines),🇵🇭
emoji=(文莱|Brunei),🇧🇳
emoji=(东帝汶|Timor-Leste),🇹🇱
emoji=(越南|Vietnam),🇻🇳
emoji=(缅甸|Myanmar),🇲🇲
emoji=(老挝|Laos),🇱🇦
emoji=(柬埔寨|Cambodia),🇰🇭
emoji=(泰国|Thailand),🇹🇭
emoji=(哈萨克斯坦|Kazakhstan),🇰🇿
emoji=(吉尔吉斯斯坦|Kyrgyzstan),🇰🇬
emoji=(塔吉克斯坦|Tajikistan),🇹🇯
emoji=(乌兹别克斯坦|Uzbekistan),🇺🇿
emoji=(土库曼斯坦|Turkmenistan),🇹🇲
emoji=(巴基斯坦|Pakistan),🇵🇰
emoji=(阿富汗|Afghanistan),🇦🇫
emoji=(阿拉伯联合酋长国|阿联酋|迪拜|Dubai),🇦🇪
emoji=(沙特阿拉伯|沙特|Saudi Arabia),🇸🇦
emoji=(也门|Yemen),🇾🇪
emoji=(巴林|Bahrain),🇧🇭
emoji=(卡塔尔|Qatar),🇶🇦
emoji=(阿曼|Oman),🇴🇲
emoji=(塞浦路斯),🇨🇾
emoji=(土耳其|TR|Turkey|Türkiye),🇹🇷
emoji=(格鲁吉亚|Georgia),🇬🇪
emoji=(亚美尼亚|Armenia),🇦🇲
emoji=(阿塞拜疆|Azerbaijan),🇦🇿
emoji=(伊朗|Iran),🇮🇷
emoji=(伊拉克|Iraq),🇮🇶
emoji=(科威特|Kuwait),🇰🇼
emoji=(以色列|Israel),🇮🇱
emoji=(巴勒斯坦|Palestine),🇵🇸
emoji=(约旦|Jordan),🇯🇴
emoji=(黎巴嫩|Lebanon),🇱🇧
emoji=(叙利亚|Syria),🇸🇾
# 非洲
emoji=(埃及|Egypt),🇪🇬
emoji=(苏丹),🇸🇩
emoji=(佛得角),🇨🇻
emoji=(摩洛哥),🇲🇦
emoji=(突尼斯),🇹🇳
emoji=(阿尔及利亚),🇩🇿
emoji=(利比亚),🇱🇾
emoji=(肯尼亚),🇰🇪
emoji=(卢旺达),🇷🇼
emoji=(布隆迪),🇧🇮
emoji=(马里),🇲🇱
emoji=(塞内加尔),🇸🇳
emoji=(科特迪瓦),🇨🇮
emoji=(加纳),🇬🇭
emoji=(多哥),🇹🇬
emoji=(贝宁),🇧🇯
emoji=(尼日利亚|Nigeria),🇳🇬
emoji=(刚果（金）|刚果民主共和国),🇨🇩
emoji=(喀麦隆),🇨🇲
emoji=(赤道几内亚),🇬🇶
emoji=(安哥拉),🇦🇴
emoji=(坦桑尼亚),🇹🇿
emoji=(莫桑比克),🇲🇿
emoji=(津巴布韦),🇿🇼
emoji=(斯威士兰),🇸🇿
emoji=(南非|South Africa),🇿🇦
emoji=(马达加斯加),🇲🇬
emoji=(留尼汪|法属留尼汪),🇷🇪
emoji=(毛里求斯),🇲🇺
# 大洋洲
emoji=(澳大利亚|澳洲|悉尼|墨尔本|AU|Australia),🇦🇺
emoji=(新西兰|New Zealand),🇳🇿
emoji=(所罗门群岛),🇸🇧
emoji=(关岛),🇬🇺
emoji=(斐济),🇫🇯
emoji=(汤加),🇹🇴
emoji=(巴布亚新几内亚),🇵🇬
# 北美洲
emoji=(百慕大),🇧🇲
emoji=(格陵兰岛|格陵兰),🇬🇱
emoji=(加拿大|CA|Canada),🇨🇦
emoji=(墨西哥|MX|Mexico),🇲🇽
emoji=(伯利兹),🇧🇿
emoji=(危地马拉),🇬🇹
emoji=(萨尔瓦多),🇸🇻
emoji=(洪都拉斯),🇭🇳
emoji=(尼加拉瓜),🇳🇮
emoji=(哥斯达黎加),🇨🇷
emoji=(巴拿马),🇵🇦
# 加勒比海周围的海上国家属于北美
emoji=(巴哈马),🇧🇸
emoji=(古巴),🇨🇺
emoji=(牙买加),🇯🇲
emoji=(海地),🇭🇹
emoji=(波多黎各),🇵🇷
emoji=(多米尼加),🇩🇴
emoji=(多米尼克),🇩🇲
emoji=(马提尼克),🇲🇶
emoji=(巴巴多斯),🇧🇧
emoji=(英属维尔京|英属维尔京群岛),🇻🇬
emoji=(开曼群岛),🇰🇾
emoji=(荷属库拉索|库拉索),🇨🇼
emoji=(特立尼达和多巴哥),🇹🇹
emoji=(阿鲁巴),🇦🇼
emoji=(瓜德罗普),🇬🇵
emoji=(安提瓜和巴布达),🇦🇬
# 南美洲
emoji=(巴西|BR|Brazil),🇧🇷
emoji=(阿根廷|AR|Argentina),🇦🇷
emoji=(巴拉圭),🇵🇾
emoji=(乌拉圭),🇺🇾
emoji=(苏里南),🇸🇷
emoji=(圭亚那),🇬🇾
emoji=(法属圭亚那),🇬🇫
emoji=(委内瑞拉),🇻🇪
emoji=(哥伦比亚|Colombia),🇨🇴
emoji=(厄瓜多尔),🇪🇨
emoji=(玻利维亚),🇧🇴
emoji=(秘鲁|Peru),🇵🇪
emoji=(智利|Chile),🇨🇱
# 南极洲
emoji=(南极|Antarctica),🇦🇶

# icon
# 🚀✈️♻️🌍🌎🌏🎯🐳🐟
# 🤖🔍🌐📲🍎Ⓜ️🧩🎬📺🎥🎮🕹️🐟⛔️🔴🔵
# 🎧🎵🎶🖥📽📹📟🎹🍭🍡🎃🎁📮🧲📬📭
# ⭐☀️🌟⚡️🔥💧❄️🌈🥊💎🔮🐹📍🥇🥈🥉


# 规则集合
# 2024-10-15，ruleset 的 “,” 之间不能有空格，Surge 识别不出来
ruleset=🇨🇳 China,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Lan/Lan.list
ruleset=🇨🇳 China,https://raw.githubusercontent.com/wmsxwdsh/ClashSub/main/customRule/AddDirect.list
ruleset=🇨🇳 China,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Logitech/Logitech.list

ruleset=REJECT,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Adobe/Adobe.list

ruleset=🍎 Apple,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Apple/Apple.list
ruleset=Ⓜ️ Microsoft,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Microsoft/Microsoft.list
ruleset=📲 Telegram,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.list

ruleset=🚀️ Flying,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Wikipedia/Wikipedia.list
ruleset=🚀️ Flying,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list
ruleset=🚀️ Flying,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Google.list
ruleset=🚀️ Flying,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Speedtest/Speedtest.list
ruleset=🚀️ Flying,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GitHub/GitHub.list
ruleset=🚀️ Flying,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Jetbrains/Jetbrains.list
ruleset=🚀️ Flying,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Shopee/Shopee.list
ruleset=🚀️ Flying,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Surge/TVB/TVB.list

ruleset=🐹 ND,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list
ruleset=🐹 ND,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/DisneyPlus.list

ruleset=🔥 Bahamut…,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Bahamut/Bahamut.list
ruleset=🔥 Bahamut…,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/HBOAsia/HBOAsia.list
ruleset=🔥 Bahamut…,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/LineTV/LineTV.list

ruleset=🤖 AiChat…,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OpenAI/OpenAI.list
ruleset=🤖 AiChat…,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/TikTok.list

ruleset=📺 Bilibili,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/BiliBili/BiliBili.list
ruleset=🕹 Game,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Steam/Steam.list

ruleset=🚀️ Flying,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ProxyLite/ProxyLite.list

ruleset=🇨🇳 China,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/China/China.list
ruleset=🇨🇳 China,[]GEOIP,CN
ruleset=🐟 Final Fishes 🐟,[]FINAL


# 这个比较全面
custom_proxy_group=🌎 Cold`select`^(?!.*(香港|HK|HKG|Hong Kong|台湾|TW|TWN|Taiwan|日本|JP|JPN|Japan|美国|US|USA|United States|新加坡|狮城|SG|SGP|Singapore))
custom_proxy_group=🇭🇰 HK`select`(香港|HK|HKG|Hong Kong)
custom_proxy_group=🇨🇳 TW`select`(台湾|TW|TWN|Taiwan)
custom_proxy_group=🇸🇬 SG`select`(新加坡|狮城|SG|SGP|Singapore)
custom_proxy_group=🇯🇵 JP`select`(日本|JP|JPN|Japan)
custom_proxy_group=🇺🇲 US`select`(美国|US|USA|United States)

custom_proxy_group=🚀️ Flying`select`[]🇭🇰 HK`[]🇨🇳 TW`[]🇸🇬 SG`[]🇯🇵 JP`[]🇺🇲 US`[]🌎 Cold
custom_proxy_group=🍎 Apple`select`[]DIRECT`[]🚀️ Flying
custom_proxy_group=Ⓜ️ Microsoft`select`[]DIRECT`[]🚀️ Flying
custom_proxy_group=📲 Telegram`select`[]🚀️ Flying`[]🇸🇬 SG`[]🇯🇵 JP`(实验性|0.01|0.1|0.2|0.25|0.5)
custom_proxy_group=🐹 ND`select`[]🇸🇬 SG`[]🇨🇳 TW`[]🚀️ Flying
custom_proxy_group=🤖 AiChat…`select`[]🇺🇲 US`[]🇨🇳 TW`[]🚀️ Flying
custom_proxy_group=🔥 Bahamut…`select`[]🇨🇳 TW`[]🚀️ Flying
custom_proxy_group=📺 Bilibili`select`[]DIRECT`[]🇨🇳 TW
custom_proxy_group=🕹 Game`select`[]DIRECT`[]🚀️ Flying`(游戏|GAME|Game)
custom_proxy_group=🇨🇳 China`select`[]DIRECT`[]🚀️ Flying
custom_proxy_group=🐟 Final Fishes 🐟`select`[]🚀️ Flying`[]DIRECT


;设置分组标志位
enable_rule_generator=true
overwrite_original_rules=true
